[workspace]
resolver = "2"

members = [
    "skar",
    "format",
    "rpc-client",
    "rpc-types",
    "ingest",
    "net-types",
    "skar-client",
]

[profile.maxperf]
inherits = "release"
lto = true
codegen-units = 1
