[package]
name = "skar-net-types"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp = "0.17.2"
serde = { version = "1", features = ["derive"] }
arrayvec = { version = "0.7", features = ["serde"] }

skar-format = { path = "../format" }

[build-dependencies]
capnpc = "0.17.2"
