name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test_dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install Cap'n Proto
      run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y capnproto libcapnp-dev
    - name: Install Rust Nightly
      run: rustup toolchain install nightly
    - name: Build
      run: cargo build --verbose --workspace
    - name: Test
      run: cargo test --verbose --workspace

  test_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install Cap'n Proto
      run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y capnproto libcapnp-dev
    - name: Install Rust Nightly
      run: rustup toolchain install nightly
    - name: Build
      run: cargo build --release --verbose --workspace
    - name: Test
      run: cargo test --release --verbose --workspace

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install Cap'n Proto
      run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y capnproto libcapnp-dev
    - name: Install Rust Nightly
      run: |
        rustup toolchain install nightly
        rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
        rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Rustfmt
      run: cargo +nightly fmt --check --verbose
    - name: Clippy
      run: cargo +nightly clippy --verbose --all-features -- -Dwarnings
